# Generated by Django 3.2.8 on 2024-02-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='category',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
