# Generated by Django 3.2.8 on 2024-02-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20240217_1702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestAdmin',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_requestadmin',
            field=models.BooleanField(default=False),
        ),
    ]
