# Generated by Django 3.2.8 on 2024-02-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_requestforproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestforproposal',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive')], default='ACTIVE', max_length=20),
        ),
    ]
