# Generated by Django 3.2.8 on 2024-02-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_vendor_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='status',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='status',
        ),
        migrations.AddField(
            model_name='category',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='requestforproposal',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='category',
        ),
        migrations.AddField(
            model_name='vendor',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='vendor_category', to='base.Category'),
        ),
    ]
