# Generated by Django 3.2.8 on 2024-02-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20240219_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
    ]
