# Generated by Django 3.2.8 on 2024-02-20 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_quotes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotes',
            old_name='rfp_no',
            new_name='rfp',
        ),
    ]
